# Generated by Django 3.0.3 on 2020-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_passwd', models.TextField()),
                ('user_ticket', models.CharField(max_length=30, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'login_info',
            },
        ),
    ]
